config/routes.rb
Rails.application.routes.draw do

  root "epicenter#feed"
  
  get 'followers' => 'epicenter#followers'
  get 'following' => 'epicenter#following'
  get 'all_users' => 'epicenter#all_users'
  get 'show_user' => 'epicenter#show_user'
  get 'now_following' => 'epicenter#now_following'
  get 'unfollow' => 'epicenter#unfollow'
  get 'tag_tweets' => 'epicenter#tag_tweets'

  resources :tweets
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :tweet_tags
    has_many :tweets, through: :tweet_tags
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user

    has_many :tweet_tags
    has_many :tags, through: :tweet_tags

    before_validation :link_check, on: :create
    validates :message, presence: true
    validates :message, length: {maximum: 280, too_long: "keep it down"}, on: :create
    after_validation :apply_link, on: :create


private

    def link_check
        if self.message.include? "https://"
            arr = self.message.split

            i = arr.map {|x| x.include? "https://"}.index(true)

            self.link = arr[i]

            if arr[i].length > 23
                arr[i] = "#{arr[i][0..20]}..."
            end

            self.message = arr.join(" ")
        end
    #link_check
    end


    def apply_link

        arr = self.message.split
        i = arr.map {|x| x.include? "https://"}.index(true)
        if i
            url = arr[i]

            arr[i] = "<a href='#{self.link}' target='_blank'>#{url}</a>"
        end
        self.message = arr.join(" ")
        


    end

# end of module    
end


# class Tweet < ApplicationRecord
#     belongs_to :user

#     has_many :tweet_tags
#     has_many :tags, through: :tweet_tags

#     before_validation :link_check, on: :create

#     validates :message, presence: true
#     validates :message, length: {maximum: 140, too_long: "A tweet is only 140 max. Everybody knows!"}

#     after_validation :apply_link, on: :create

#     private

#     def link_check
#         if self.message.include? "http://" || "https://" 
#             arr = Array.new
#             arr = self.message.split

#             index = arr.map { |x| x.include? "http://" }.index(true)

#             self.link = arr[index]
            
#             if arr[index].length > 23
#                 arr[index] = "#{arr[index][0..20]}..."
#             end

#             self.message = arr.join(" ")
#         end
#     end

#     def apply_link
#         arr = Array.new
#         arr = self.message.split
#         index = arr.map{ |x| x.include? "http://" }.index(true)
#         url = arr[index]

#         arr[index] = "<a href='#{self.link}' target='_blank'>#{url}</a>"

#         self.message = arr.join(" ")
#     end


# end

app/models/tweet_tag.rb
class TweetTag < ApplicationRecord
    belongs_to :tweet
    belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :tweets

  serialize :following, Array

  #carrierwave
  mount_uploader :avatar, AvatarUploader
  
  #validation
  validates :username, presence: true
  validates :username, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    #protects from scrf attack
    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    before_action :authenticate_user!

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up,
             keys: [:username, :name, :bio, :location, :avatar, :following])
        devise_parameter_sanitizer.permit(:account_update,
             keys: [:username, :name, :bio, :location, :avatar, :following])
    end
end

app/controllers/epicenter_controller.rb
class EpicenterController < ApplicationController
    
    def feed
      @following_tweets = []
  # change if current_user.following. to current_user.now_following
      Tweet.all.each do |tweet|
        if current_user.following.include?(tweet.user_id) || current_user.id == tweet.user_id
          @following_tweets.push(tweet)
        end
      end
  end

    def show_user
      @user = User.find(params[:id])
    end

    def now_following
      current_user.following.push(params[:id].to_i)
      current_user.save

      redirect_to show_user_path(id: params[:id])
    end

    def unfollow
      current_user.following.delete(params[:id].to_i)
      current_user.save

      redirect_to show_user_path(id: params[:id])
    end
  

  def tag_tweets
    @tag = Tag.find(params[:id])
  end

  def all_users
    @users = User.all
  end

  def following
    @user = User.find(params[:id])
    @users = []

    User.all.each do |user|
      if @user.following.include?(user.id)
        @users.push(user)
      end
    end
  end

  def followers
    @user =  User.find(params[:id])
    @users = []

    User.all.each do |user|
      if user.following.include?(@user.id)
        @users.push(user)
      end
    end
  end


end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  #keep users who are not signed-in out 
  before_action :authenticate_user!

  include TweetsHelper

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = @tweet = Tweet.create(tweet_params)  
    
    @tweet = get_tagged(@tweet)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:message, :user_id, :link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def profile_pic(user)
        if user.avatar.url != nil
            user.avatar.url
        else
            'kitten.jpg'
        end
    end
 
end

app/helpers/epicenter_helper.rb
module EpicenterHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
    def get_tagged(tweet)
        message_arr = Array.new
        message_arr = tweet.message.split
        message_arr.each_with_index do |word, index|
            if word[0] == "#"
                if Tag.pluck(:phrase).include?(word)
                    tag = Tag.find_by(phrase: word)
                else
                    tag = Tag.create(phrase: word)
                end
                tweet_tag = TweetTag.create(tweet_id: @tweet.id, tag_id: tag.id)
                message_arr[index] = "<a href='/tag_tweets?id=#{tag.id}'>#{word}</a>"
            end
        end

        tweet.message = message_arr.join(" ")
        return tweet
    end
    
end

app/views/epicenter/_user_list.html.erb
<div class="row">
  <% @users.each do |user| %>
  <div class="col-md-3">
    <div class="well user-list-wells">
      <div class="row">
        <div class="col-md-6">
          <%= image_tag profile_pic(user), class: "user-pic-md" %>
        </div>
        <div class="col-md-6">
          <p>
            <% if current_user.following.include?(user.id) %>
            <%= link_to "Following", unfollow_path(id: user.id), class: "btn btn-primary", id: "unfollow_btn" %>
            <% else %>
            <% if current_user.id != user.id %>
            <%= link_to "Follow", now_following_path(id: user.id), class: "btn btn-primary" %>
            <% end %>
            <% end %>
          </p>
        </div>
      </div>
      <div class="row">
        <%= link_to show_user_path(id: user.id) do %>
        <h3><%= user.name %></h3>
        <p>@<%= user.username %></p>
        <% end %>
        <p>
          <%= user.bio %>
        </p>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/epicenter/all_users.html.erb
<%= render 'user_list' %>

app/views/epicenter/feed.html.erb
<!-- header pic -->
<%= image_tag("/assets/sunset.jpg",  alt: "like", class: "img-responsive imgtop") %>


<!--profile picture-->
<%= image_tag profile_pic(current_user), class: "user-pic-md img-circle" %>


<!-- content starts -->
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <h1>  <%= current_user.username %> </h1>
            <p>
                @<%= current_user.username %><br />
                <%= current_user.bio %>

            </p>
            <ul class="twitlist">
                <li class="litwitlist"><i class="glyphicon glyphicon-map-marker"></i> 
                    <%= current_user.location %>
                </li>
                <li class="litwitlist"><i class="glyphicon glyphicon-link"></i> about.twitter.com</li>
                <li class="litwitlist"><i class="glyphicon glyphicon-map-marker"></i> View Broadcast</li>
                <li class="litwitlist"><i class="glyphicon glyphicon-calendar"></i> Joined </li>
                <li class="litwitlist"><i class="glyphicon glyphicon-gift"></i> Celebrate</li>
                <li class="litwitlist"><i class="glyphicon glyphicon-picture"></i> Pictures</li>
            </ul>
        </div>


        <!-- middle -->

        <div class="col-md-6 middlecont topper">
            <% @following_tweets.each do |tweet| %>
            <%= render  "tweets/tweet", tweet: tweet %>
           <% end %>

        </div>

        <!--row 3-->
        <div class="col-md-3">
            <div class="well text-center">
                <h1>New To Twitter?</h1>
                <p>
                    Find friends now! <br> Click below! <br /><br />
                    <button type="button" class="btn btn-primary btn-lg active">
                            <%= link_to "Find Users", :all_users %>
                    </button>
                </p>
            </div>
            <div class="well text-center">
                <h1>You May Also Like?</h1>
                <p>
                    <br>
                    Follow these cool accouunts now!<br />
                    <br /><br />
                    <span class="bold">
                        <img src="https://68ef2f69c7787d4078ac-7864ae55ba174c40683f10ab811d9167.ssl.cf1.rackcdn.com/youtube-icon_64x64.png"
                            alt="" srcset=""> Youtube @youtube
                        <br><br>
                        <img src="https://68ef2f69c7787d4078ac-7864ae55ba174c40683f10ab811d9167.ssl.cf1.rackcdn.com/twitter-icon_64x64.png"
                            alt="" srcset=""> Twitter @twitter
                    </span>
                </p>

            </div>

            <footer>
                <ul class="footer">
                    <li class="footerli"> policy </li>
                    <li class="footerli"> help </li>
                    <li class="footerli"> contact </li>
                    <li class="footerli"> resources </li>
                </ul>
        </footer>
        </div>
        
    </div>
</div>

app/views/epicenter/followers.html.erb
<h2>
    <%= @user.name %>'s Followers
</h2>

<%= render 'user_list' %>

app/views/epicenter/following.html.erb
<h2>
    <%= @user.name %> is following:
</h2>
    
    <%= render 'user_list' %>

app/views/epicenter/now_following.html.erb
<div class="container">
    <div class="well">
        

<h1>Epicenter#now_following</h1>
<p>Find me in app/views/epicenter/now_following.html.erb</p>

    </div>
</div>

app/views/epicenter/show_user.html.erb
<!-- header pic -->
<%= image_tag("/assets/sunset.jpg",  alt: "like", class: "img-responsive imgtop") %>

<!--profile picture-->
<%= image_tag profile_pic(@user), class: "user-pic-md img-circle" %>

<!-- content starts -->

<div class="container">
    <div class="row">
        <div class="col-md-3">
            <h1><%= @user.username %></h1>
            <p>
                @<%= @user.username %><br />
                <br>
                <%= @user.bio %>

            </p>
            <ul class="twitlist">
                <li class="litwitlist"><i class="glyphicon glyphicon-map-marker"></i> 
                    <%= @user.location %>
                </li>
                <li class="litwitlist"><i class="glyphicon glyphicon-link"></i> about.twitter.com</li>
                <li class="litwitlist"><i class="glyphicon glyphicon-map-marker"></i> View Broadcast</li>
                <li class="litwitlist"><i class="glyphicon glyphicon-calendar"></i> Joined </li>
                <li class="litwitlist"><i class="glyphicon glyphicon-gift"></i> Celebrate</li>
                <li class="litwitlist"><i class="glyphicon glyphicon-picture"></i> Pictures</li>
            </ul>
        </div>

<!-- middle start -->

    <div class="col-md-6 middlecont topper">
        <% @user.tweets.each do |tweet| %>
           <%= render  "tweets/tweet", tweet: tweet %>

        <% end %>
    </div>



        <!--row 3-->
        <div class="col-md-3">
            <div class="well text-center">
                <h1>New To Twitter?</h1>
                <p>
                        Find friends now! <br> Click below! <br /><br />
                        <button type="button" class="btn btn-primary btn-lg active">
                                <%= link_to "Find Users", :all_users %>
                        </button>
                    </p>
            </div>
            <div class="well text-center">
                <h1>You May Also Like?</h1>
                <p>
                    <br>
                    Follow these cool accouunts now!<br />
                    <br /><br />
                    <span class="bold">
                        <img src="https://68ef2f69c7787d4078ac-7864ae55ba174c40683f10ab811d9167.ssl.cf1.rackcdn.com/youtube-icon_64x64.png"
                            alt="" srcset=""> Youtube @youtube
                        <br><br>
                        <img src="https://68ef2f69c7787d4078ac-7864ae55ba174c40683f10ab811d9167.ssl.cf1.rackcdn.com/twitter-icon_64x64.png"
                            alt="" srcset=""> Twitter @twitter
                    </span>
                </p>

            </div>

            <footer>
                <ul class="footer">
                    <li class="footerli"> policy </li>
                    <li class="footerli"> help </li>
                    <li class="footerli"> contact </li>
                    <li class="footerli"> resources </li>
                </ul>
        </footer>
        </div>
        
    </div>
</div>

app/views/epicenter/tag_tweets.html.erb
<div class="container tag_page">
    <div class="well"> 

<div>
    <h1><%= @tag.phrase %></h1>
</div>

<div class="row">
    <div>
        <% @tag.tweets.order(created_at: :desc).each do |tweet| %>
            <p>
                <%= tweet.user.name %> <%= "@#{tweet.user.username}" %>
                <%= time_ago_in_words(tweet.created_at) %>
            </p>
            <p>
                <%= tweet.message.html_safe %>
            </p>
        <% end %>
    </div>
</div>

</div>
</div>

app/views/epicenter/unfollow.html.erb
<div class="container">
    <div class="well">
        

<h1>Epicenter#unfollow</h1>
<p>Find me in app/views/epicenter/unfollow.html.erb</p>

    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTwitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<body>


    
  <nav class="navbar navbar-default">
    <!-- change div container-fluid to container -->
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <!-- <%= link_to "Home", root_path, class: "navbar-brand" %> -->
        <div class="eyebox">
        <span class="eye"><%= link_to '<i class="glyphicon glyphicon-eye-open"></i>'.html_safe, root_path %></span>
</div>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "Compose New Tweet", new_tweet_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <% if profile_pic(current_user).blank? == false %>
                <%= image_tag profile_pic(current_user), class: "user-pic-md nav-avatar" %>
                <% end %> 
                @<%= current_user.username %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
 
    <div >
        <%= yield %>
      </div>
    </div>


</body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :message, placeholder: "What's happening?", class: "form-control" %>
  </div>

  <div class="field">
     <%= form.hidden_field :user_id, value: current_user.id %> 
  
  </div>

  <div class="form-group">
    <%= form.submit "Tweet It!", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tweets/_media_icons.html.erb
<div class="container">
  <div class="text-center center-block">
    <p class="txt-railway">- Bootsnipp.com -</p>
    <br />
    <a href="https://www.facebook.com/bootsnipp"
      ><i class="fa fa-facebook-square fa-3x social" id="social-fb"></i
    ></a>
    <a href="https://twitter.com/bootsnipp"
      ><i class="fa fa-twitter-square fa-3x social"></i
    ></a>
    <a href="https://plus.google.com/+Bootsnipp-page"
      ><i class="fa fa-google-plus-square fa-3x social"></i
    ></a>
    <a href="mailto:bootsnipp@gmail.com"
      ><i class="fa fa-envelope-square fa-3x social"></i
    ></a>
  </div>
</div>

app/views/tweets/_tweet.html.erb
<% if local_assigns[:tweet] %>
    <% @tweet = tweet %>
    <% end %>


        <div class="well">
            <p>
                <%= link_to tweet.user.name, show_user_path(id: tweet.user_id) %>
                @<%= link_to tweet.user.username, show_user_path(id: tweet.user_id) %>
                <%= time_ago_in_words(tweet.created_at) if Time.now - tweet.created_at < 86400 %>
                <%= tweet.created_at.strftime('%b%e') if Time.now - tweet.created_at > 86400 %>
            </p>
            <p><%= tweet.message.html_safe %></p>
        </div>

app/views/tweets/edit.html.erb
<div class="container edit-page">
    <div class="well">
        
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

    </div>
</div>

app/views/tweets/index.html.erb
<div class="container all_tweets_page">
  <div class="well">
   

<p id="notice"><%= notice %></p>

<h1>Tweets</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.message.html_safe %></td>
        <td><%= link_to tweet.user.username, show_user_path(id: tweet.user.id) %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>
 
  </div>
</div>

app/views/tweets/new.html.erb
<div class="container">
<div class="container new_tweet">
<div class="well">
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>
</div>

</div></div>

app/views/tweets/show.html.erb
<div class="container new_tweet_page">
  <div class="well">


<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @tweet.message %>
</p>

<p>
  <strong>User:</strong>
  <%= link_to @tweet.user.username, show_user_path(id: @tweet.user.id) %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>
 
</div>
</div>